spring:
  application:
    name: spring-demo-kt
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MYSQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#        use_sql_comments: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
logging:
  level:
    com.linecorp.kotlinjdsl: DEBUG